define(['paths'],function(){
    require([
        'AbstractGrid',
        'Animation',
        'AppObject',
        'CanvasEngine',
        'CanvasLayer',
        'Color',
        'Filter',
        'Frame',
        'FrameSync',
        'Grid',
        'ImageSet',
        'Map',
        'ObjectLayer',
        'RectSet',
        'KeyReader',
        'MouseReader',
        'jquery',
        'Math',
        'Overlap',
        'lodash'
    ],function(
        Animation,
        CanvasEngine,
        CanvasLayer,
        Color,
        Filter,
        Frame,
        FrameSync,
        Grid,
        ImageSet,
        Map,
        ObjectLayer,
        RectSet,
        KeyReader,
        MouseReader
    ){
        return {
            Animation:Animation,
            CanvasEngine:CanvasEngine,
            CanvasLayer:CanvasLayer,
            Color:Color,
            Filter:Filter,
            Frame:Frame,
            FrameSync:FrameSync,
            Grid:Grid,
            ImageSet:ImageSet,
            Map:Map,
            ObjectLayer:ObjectLayer,
            RectSet:RectSet,
            KeyReader:KeyReader,
            MouseReader:MouseReader
        };
    });
});