requirejs.config({
    "urlArgs": "bust=" + (new Date()).getTime(),
    "paths":{
        "AppObject":"src/core/AppObject",
        "CanvasEngine":"src/core/CanvasEngine",
        "CanvasLayer":'src/core/CanvasLayer',
        "Math":"bower_components/MathLib/src/Math",
        "MouseReader":"src/Reader/MouseReader",
        "jquery-tmp":"bower_components/jquery/dist/jquery.min",
        "jquery":"src/jquery"
    },
    "shim":{
        "jquery":{
            deps:["jquery-tmp"]
        },
        "CanvasEngine":{
            deps:["CanvasLayer"]
        }
    }
});